=== itsDaiton/xml-project/posd03_schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"  
            targetNamespace="https://www.posd03-ns.cz/LS2021"
            xmlns="https://www.posd03-ns.cz/LS2021"
            xmlns:prefix="https://www.posd03-ns.cz/LS2021"
            elementFormDefault="qualified">      
    
    <!-- ID občanského průkazu musí být 9 ciferné číslo. -->
    <xsd:simpleType name="idType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="\d{9}"/>
        </xsd:restriction>
    </xsd:simpleType>
      
    <!-- Rodné číslo musí formát českého rodného čísla. -->
    <xsd:simpleType name="rodne_cisloType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9]{6}\/[0-9]{4}"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <!-- Jméno musí mít délku mezi 1 až 16 znaky. -->
    <xsd:simpleType name="jmenoType">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="1"/>
            <xsd:maxLength value="16"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <!-- Příjmení musí mít delků mezi 1 až 20 znaky. -->
    <xsd:simpleType name="prijmeniType">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="1"/>
            <xsd:maxLength value="20"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <!-- Pohlaví musí být žena nebo muž. -->
    <xsd:simpleType name="pohlaviType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Muž"/>
            <xsd:enumeration value="Žena"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <!-- Rodinný stav musí být jedna z následujících možností. -->
    <xsd:simpleType name="rodinny_stavType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="svobodný"/>
            <xsd:enumeration value="ženatý"/>
            <xsd:enumeration value="rozvedený"/>
            <xsd:enumeration value="vdovec"/>
            <xsd:enumeration value="svobodná"/>
            <xsd:enumeration value="vdaná"/>
            <xsd:enumeration value="rozvedená"/>
            <xsd:enumeration value="vdova"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <!-- Atribut typ u datumu musí mít jedna z následujících možností. -->
    <xsd:simpleType name="datumTypType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="narozeni"/>
            <xsd:enumeration value="vydani"/>
            <xsd:enumeration value="vyprseni"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <!-- Den musí mít hodnoty mezi 1 až 31. -->
    <xsd:simpleType name="denType">
        <xsd:restriction base="xsd:int">
            <xsd:minInclusive value="1"/>
            <xsd:maxInclusive value="31"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <!-- Měsíc musí mít hodnoty mezi 1 až 12. -->
    <xsd:simpleType name="mesicType">
        <xsd:restriction base="xsd:int">
            <xsd:minInclusive value="1"/>
            <xsd:maxInclusive value="12"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <!-- Rok je číslo s minimální hodnotou 1900. -->
    <xsd:simpleType name="rokType">
        <xsd:restriction base="xsd:int">
            <xsd:minInclusive value="1900"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <!-- Obecný formát využivaný pro ulici, město, obvod... První písmeno velké a zbytek malé. -->
    <xsd:simpleType name="mistoStringType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="(\p{Lu}\p{Ll}+ \p{Lu}\p{Ll}+)|(\p{Lu}\p{Ll}+)"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <!-- První písmeno velké a zbytek malé nebo první písmeno velké mezera a zbytek malé písmena. -->
    <xsd:simpleType name="obcanstviType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="(\p{Lu}\p{Ll}+ \p{Ll}+)|(\p{Lu}\p{Ll}+)"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <!-- Atribut v adrese musí mít vždy hodnotu "postovni". -->
    <xsd:simpleType name="adresaDruhType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="postovni"></xsd:pattern>
        </xsd:restriction>
    </xsd:simpleType>
    
    <!-- Číslo popisné může být jakékoliv celé číslo větší než 0. -->
    <xsd:simpleType name="cpType">
        <xsd:restriction base="xsd:int">
            <xsd:minExclusive value="0"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <!-- Podobný jako občanství, s rozdílem že lze zadat slova oddělena pomlčkou, např. Praha-Západ. -->
    <xsd:simpleType name="okresType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="(\p{Lu}\p{Ll}+ \p{Ll}+)|(\p{Lu}\p{Ll}+)|(\p{Lu}\p{Ll}+-\p{Lu}\p{Ll}+)"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <!-- Textový řetězec minimálně s jedním znakem, maximálně s 100 znaky. -->
    <xsd:simpleType name="vydavatelType">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="1"/>
            <xsd:maxLength value="100"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:complexType name="osobni_udajeType">
        <xsd:sequence>
            <xsd:element name="jmeno" type="jmenoType"/>
            <xsd:element name="prijmeni" type="prijmeniType"/>
            <xsd:element name="pohlavi" type="pohlaviType"/>
            <xsd:element name="rodinny_stav" type="rodinny_stavType"/>
        </xsd:sequence>
        <xsd:attribute name="rodne_cislo" type="rodne_cisloType" use="required"/>
    </xsd:complexType>
    
    <xsd:complexType name="datumType">
        <xsd:sequence>
            <xsd:element name="den" type="denType"/>
            <xsd:element name="mesic" type="mesicType"/>
            <xsd:element name="rok" type="rokType"/>
        </xsd:sequence>
        <xsd:attribute name="typ" type="datumTypType" use="required"/>
    </xsd:complexType>
    
    <xsd:complexType name="mistoType">
        <xsd:sequence>
            <xsd:element name="mesto" type="mistoStringType"/>
            <xsd:element name="obvod" type="mistoStringType"/>
        </xsd:sequence>
    </xsd:complexType>   
    
    <xsd:complexType name="adresaType">
        <xsd:sequence>
            <xsd:element name="mesto" type="mistoStringType"/>
            <xsd:element name="ulice" type="mistoStringType"/>
            <xsd:element name="cp" type="cpType"/>
            <xsd:element name="okres" type="okresType"/>
        </xsd:sequence>
        <xsd:attribute name="druh" type="adresaDruhType" use="required"/>
    </xsd:complexType>
    
    <xsd:complexType name="platnostType">
        <xsd:sequence>
            <xsd:element name="datum" type="datumType" maxOccurs="2"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="narozeniType">
        <xsd:sequence>
            <xsd:element name="datum" type="datumType"/>
            <xsd:element name="misto" type="mistoType"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="obcansky_prukazType">       
        <xsd:sequence>
            <xsd:element name="osobni_udaje" type="osobni_udajeType" maxOccurs="1"/>
            <xsd:element name="narozeni" type="narozeniType" maxOccurs="1"/>
            <xsd:element name="obcanstvi" type="obcanstviType" maxOccurs="1"/>
            <xsd:element name="platnost" type="platnostType" maxOccurs="1"/>
            <xsd:element name="adresa" type="adresaType" maxOccurs="1"/>
            <xsd:element name="vydavatel" type="vydavatelType" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="idType" use="required"/>
    </xsd:complexType>
    
    <xsd:element name="obcansky_prukaz" type="obcansky_prukazType">     
        
        <!-- Občanské průkazy musí mít unikatní ID. -->
        <xsd:key name="idKlic">
            <xsd:selector xpath="prefix:obcansky_prukaz"/>
            <xsd:field xpath="@id"/>
        </xsd:key>     
        
        <!-- Datumy v platnosti nesmí mít stejné typy. -->
        <xsd:key name="unikatniTypyDatumu">
            <xsd:selector xpath="prefix:platnost/prefix:datum"/>
            <xsd:field xpath="@typ"/>
        </xsd:key>
        
    </xsd:element>
    
</xsd:schema>

=== itsDaiton/xml-project/posd03_dokument3.xml
<?xml version="1.0" encoding="UTF-8"?>
<obcansky_prukaz xmlns="https://www.posd03-ns.cz/LS2021"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.posd03-ns.cz/LS2021 posd03_schema.xsd"
    id="602397400">
    <osobni_udaje rodne_cislo="500111/3658">
        <jmeno>František</jmeno>
        <prijmeni>Odvarka</prijmeni>
        <pohlavi>Muž</pohlavi>
        <rodinny_stav>rozvedený</rodinny_stav>
    </osobni_udaje>
    <narozeni>
        <datum typ="narozeni">
            <den>1</den>
            <mesic>11</mesic>
            <rok>1950</rok>
        </datum>
        <misto>
            <mesto>Česká Skalice</mesto>
            <obvod>Velká Jesenice</obvod>
        </misto>
    </narozeni>
    <obcanstvi>Česká republika</obcanstvi>
    <platnost>
        <datum typ="vydani">
            <den>10</den>
            <mesic>1</mesic>
            <rok>1980</rok>
        </datum>
        <datum typ="vyprseni">
            <den>10</den>
            <mesic>1</mesic>
            <rok>1990</rok>
        </datum>
    </platnost>
    <adresa druh="postovni">
        <mesto>Karlovy Vary</mesto>
        <ulice>Upsaná</ulice>
        <cp>12</cp>
        <okres>Nejdek-Vary</okres>
    </adresa>
    <vydavatel>Magistrát města Karlovy Vary</vydavatel>
</obcansky_prukaz>

=== itsDaiton/xml-project/posd03_dokument1.xml
<?xml version="1.0" encoding="UTF-8"?>
<obcansky_prukaz xmlns="https://www.posd03-ns.cz/LS2021"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.posd03-ns.cz/LS2021 posd03_schema.xsd"
    id="248699316">
    <osobni_udaje rodne_cislo="980707/0594">
        <jmeno>Ondřej</jmeno>
        <prijmeni>Rychlý</prijmeni>
        <pohlavi>Muž</pohlavi>
        <rodinny_stav>svobodný</rodinny_stav>
    </osobni_udaje>
    <narozeni>
        <datum typ="narozeni">
            <den>7</den>
            <mesic>7</mesic>
            <rok>1998</rok>
        </datum>
        <misto>
            <mesto>Praha</mesto>
            <obvod>Žižkov</obvod>
        </misto>
    </narozeni>
    <obcanstvi>Česká republika</obcanstvi>
    <platnost>
        <datum typ="vydani">
            <den>19</den>
            <mesic>2</mesic>
            <rok>2018</rok>
        </datum>
        <datum typ="vyprseni">
            <den>19</den>
            <mesic>2</mesic>
            <rok>2028</rok>
        </datum>
    </platnost>
    <adresa druh="postovni">
        <mesto>Jesenice</mesto>
        <ulice>Okružní</ulice>
        <cp>1289</cp>
        <okres>Praha-Západ</okres>
    </adresa>
    <vydavatel>UMČ Praha 11</vydavatel>
</obcansky_prukaz>

=== itsDaiton/xml-project/posd03_dokument4.xml
<?xml version="1.0" encoding="UTF-8"?>
<obcansky_prukaz xmlns="https://www.posd03-ns.cz/LS2021"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.posd03-ns.cz/LS2021 posd03_schema.xsd"
    id="552945357">
    <osobni_udaje rodne_cislo="005319/1498">
        <jmeno>Veronika</jmeno>
        <prijmeni>Nováková</prijmeni>
        <pohlavi>Žena</pohlavi>
        <rodinny_stav>svobodná</rodinny_stav>
    </osobni_udaje>
    <narozeni>
        <datum typ="narozeni">
            <den>19</den>
            <mesic>3</mesic>
            <rok>2000</rok>
        </datum>
        <misto>
            <mesto>Praha</mesto>
            <obvod>Vinohrady</obvod>
        </misto>
    </narozeni>
    <obcanstvi>Česká republika</obcanstvi>
    <platnost>
        <datum typ="vydani">
            <den>25</den>
            <mesic>5</mesic>
            <rok>2015</rok>
        </datum>
        <datum typ="vyprseni">
            <den>25</den>
            <mesic>5</mesic>
            <rok>2025</rok>
        </datum>
    </platnost>
    <adresa druh="postovni">
        <mesto>Nymburk</mesto>
        <ulice>Česká</ulice>
        <cp>1900</cp>
        <okres>Nymburk-Jih</okres>
    </adresa>
    <vydavatel>Městský úrad Nymburk</vydavatel>
</obcansky_prukaz>

=== itsDaiton/xml-project/posd03_dokument2.xml
<?xml version="1.0" encoding="UTF-8"?>
<obcansky_prukaz xmlns="https://www.posd03-ns.cz/LS2021"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.posd03-ns.cz/LS2021 posd03_schema.xsd"
    id="741598771">
    <osobni_udaje rodne_cislo="816214/1234">
        <jmeno>Anna</jmeno>
        <prijmeni>Pomalá</prijmeni>
        <pohlavi>Žena</pohlavi>
        <rodinny_stav>vdaná</rodinny_stav>
    </osobni_udaje>
    <narozeni>
        <datum typ="narozeni">
            <den>14</den>
            <mesic>12</mesic>
            <rok>1981</rok>
        </datum>
        <misto>
            <mesto>Brno</mesto>
            <obvod>Bosonohy</obvod>
        </misto>
    </narozeni>
    <obcanstvi>Česká republika</obcanstvi>
    <platnost>
        <datum typ="vydani">
            <den>16</den>
            <mesic>10</mesic>
            <rok>2016</rok>
        </datum>
        <datum typ="vyprseni">
            <den>16</den>
            <mesic>10</mesic>
            <rok>2026</rok>
        </datum>
    </platnost>
    <adresa druh="postovni">
        <mesto>Pardubice</mesto>
        <ulice>Hranatá</ulice>
        <cp>500900</cp>
        <okres>Pardubice-Sever</okres>
    </adresa>
    <vydavatel>Pardubice - magistrát města</vydavatel>
</obcansky_prukaz>

=== itsDaiton/xml-project/posd03_dokument6.xml
<?xml version="1.0" encoding="UTF-8"?>
<obcansky_prukaz xmlns="https://www.posd03-ns.cz/LS2021"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.posd03-ns.cz/LS2021 posd03_schema.xsd"
    id="614889331">
    <osobni_udaje rodne_cislo="560920/6378">
        <jmeno>Antonín</jmeno>
        <prijmeni>Zpěvák</prijmeni>
        <pohlavi>Muž</pohlavi>
        <rodinny_stav>ženatý</rodinny_stav>
    </osobni_udaje>
    <narozeni>
        <datum typ="narozeni">
            <den>20</den>
            <mesic>9</mesic>
            <rok>1956</rok>
        </datum>
        <misto>
            <mesto>Opava</mesto>
            <obvod>Otice</obvod>
        </misto>
    </narozeni>
    <obcanstvi>Česká republika</obcanstvi>
    <platnost>
        <datum typ="vydani">
            <den>26</den>
            <mesic>11</mesic>
            <rok>2004</rok>
        </datum>
        <datum typ="vyprseni">
            <den>26</den>
            <mesic>11</mesic>
            <rok>2014</rok>
        </datum>
    </platnost>
    <adresa druh="postovni">
        <mesto>Olomouc</mesto>
        <ulice>Kulatá</ulice>
        <cp>1523</cp>
        <okres>Jeseník</okres>
    </adresa>
    <vydavatel>Magistrát města Olomouce</vydavatel>
</obcansky_prukaz>

=== itsDaiton/xml-project/posd03_dokument5.xml
<?xml version="1.0" encoding="UTF-8"?>
<obcansky_prukaz xmlns="https://www.posd03-ns.cz/LS2021"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.posd03-ns.cz/LS2021 posd03_schema.xsd"
    id="156287954">
    <osobni_udaje rodne_cislo="891026/9323">
        <jmeno>Šimon</jmeno>
        <prijmeni>Procházka</prijmeni>
        <pohlavi>Muž</pohlavi>
        <rodinny_stav>svobodný</rodinny_stav>
    </osobni_udaje>
    <narozeni>
        <datum typ="narozeni">
            <den>26</den>
            <mesic>10</mesic>
            <rok>1989</rok>
        </datum>
        <misto>
            <mesto>Ostrava</mesto>
            <obvod>Krásné Pole</obvod>
        </misto>
    </narozeni>
    <obcanstvi>Česká republika</obcanstvi>
    <platnost>
        <datum typ="vydani">
            <den>5</den>
            <mesic>12</mesic>
            <rok>2011</rok>
        </datum>
        <datum typ="vyprseni">
            <den>5</den>
            <mesic>12</mesic>
            <rok>2021</rok>
        </datum>
    </platnost>
    <adresa druh="postovni">
        <mesto>Třeboň</mesto>
        <ulice>Kapří</ulice>
        <cp>1000</cp>
        <okres>Třebon-Lužnice</okres>
    </adresa>
    <vydavatel>Úřad města Třeboň</vydavatel>
</obcansky_prukaz>
